#!/bin/sh
# UMO VNC Session — {{UMO_VERSION}}
export PULSE_SERVER=127.0.0.1
export PULSE_LATENCY_MSEC=30
export DISPLAY={{DISPLAY}}
export XAUTHORITY="$HOME/.Xauthority"

xset s off
xset -dpms
xset s noblank

DE="{{UMO_DE}}"
case "$DE" in
    lxde)
        [ -x "$(command -v startlxde)" ] && \
            exec dbus-launch --exit-with-session startlxde ;;
    xfce4|xfce)
        [ -x "$(command -v startxfce4)" ] && \
            exec dbus-launch --exit-with-session startxfce4 ;;
    openbox)
        [ -x "$(command -v openbox-session)" ] && \
            exec dbus-launch --exit-with-session openbox-session ;;
    *)
        [ -x "$(command -v startxfce4)" ] && exec dbus-launch --exit-with-session startxfce4
        [ -x "$(command -v startlxde)" ]  && exec dbus-launch --exit-with-session startlxde
        xterm & exec twm ;;
esac